### ISSUE TITLE
API call example

### ISSUE THREAD

**Issue by victorcarvalhosp** [oknoorap/mobx-react-lite-context#5]
Hi team,

It's possible to provide an example on the recommended way to do an API call in this example: https://codesandbox.io/s/mobx-react-lite-context-3iwcu ?

**Comment by oknoorap** [comment]
@victorcarvalhosp it's just like standard mobx, you can make API call with mobx store class.

**Comment by victorcarvalhosp** [comment]
I was a bit lost when I opened this here. It's all good now, thanks!
