### ISSUE TITLE
How to use one store inside another store?

### ISSUE THREAD

**Issue by victorcarvalhosp** [oknoorap/mobx-react-lite-context#6]
Hi,

First of all, thanks for implementing this awesome library, after struggling to create a context to use with mobx I found this and it worked like a charm. Now I just don't know yet how can I use one store inside another store...

Can you provide an example? You can use the same code from the codesandbox https://codesandbox.io/s/mobx-react-lite-context-3iwcu, but using the counter store inside the ui store, just for the sake of the example.

Appreciate!

Yours,
Victor

**Comment by oknoorap** [comment]
Just wrap your app with multiple provider 😄
